// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJx9S_A_rvsGV1TTFLwU0k1sJiogoGit8',
    appId: '1:709557751572:web:9d3a410e17f1b96d7afc01',
    messagingSenderId: '709557751572',
    projectId: 'chatapp-9224e',
    authDomain: 'chatapp-9224e.firebaseapp.com',
    storageBucket: 'chatapp-9224e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCcbOzU3wZ_JO0M7QI0f2oX4hbrMVosDk',
    appId: '1:709557751572:android:48dddd457775f2e47afc01',
    messagingSenderId: '709557751572',
    projectId: 'chatapp-9224e',
    storageBucket: 'chatapp-9224e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBivEjuDPOWBL7IFcNKD6bMJ7SbAeV0wgs',
    appId: '1:709557751572:ios:c14cdcec4b6515d17afc01',
    messagingSenderId: '709557751572',
    projectId: 'chatapp-9224e',
    storageBucket: 'chatapp-9224e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBivEjuDPOWBL7IFcNKD6bMJ7SbAeV0wgs',
    appId: '1:709557751572:ios:eed289ec6b9835e17afc01',
    messagingSenderId: '709557751572',
    projectId: 'chatapp-9224e',
    storageBucket: 'chatapp-9224e.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
